services:
  app:
    image: ghcr.io/fres-sudo/pomo-server:latest
    container_name: pomo-backend
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 9000:9000
    restart: always
    networks:
      - app-network

  postgres:
    container_name: pomo-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_INTERVAL=30
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
